Vagrant.configure("2") do |config|

  # Kubernetes Controllers
  (1..3).each do |i|
    config.vm.define "controller-#{i}" do |node|
      node.vm.box         = "fedora/28-cloud-base"
      node.vm.box_version = "20180425"
      node.vm.hostname    = "controller-#{i}"

      node.vm.network "private_network", ip: "192.168.10.#{i+1}"
      node.vm.provision "shell", path: "scripts/locale.sh"
      node.vm.provision "shell", path: "scripts/selinux.sh"
      node.vm.provision "shell", path: "scripts/etcd.sh"
      node.vm.provision "shell", path: "scripts/controller.sh"

      node.vm.provider "virtualbox" do |vb|
          vb.memory = "2048"
      end
    end
  end

  # Kubernetes workers
  (1..3).each do |i|
    config.vm.define "worker-#{i}" do |node|
      node.vm.box         = "fedora/28-cloud-base"
      node.vm.box_version = "20180425"
      node.vm.hostname    = "worker-#{i}"

      node.vm.network "private_network", ip: "192.168.20.#{i+1}"
      node.vm.provision "shell", path: "scripts/locale.sh"
      node.vm.provision "shell", path: "scripts/selinux.sh"
      node.vm.provision "shell", path: "scripts/ca.sh"
      node.vm.provision "shell", path: "scripts/worker.sh", args: "10.200.#{i+1}.0/24"

      node.vm.provider "virtualbox" do |vb|
          vb.memory = "1024"
      end
    end
  end

end
